# iCloudPD — iCloud Photos downloader.
# https://github.com/icloud-photos-downloader/icloud_photos_downloader

name: icloudpd

services:
  icloudpd:
    image: icloudpd/icloudpd:1.32.2@sha256:eb5fad6a58dc77ffa8c87d47078df28269959726eb58ed23502d27f6c6976c94

    restart: unless-stopped
    init: true

    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

    networks:
      - icloudpd

    environment:
      TZ: ${TZ:-Europe/Warsaw}

    volumes:
      - ${ICLOUDPD_DOWNLOAD_PATH:-/tmp/icloudpd}:/data
      - icloudpd-cookies:/cookies

    command: >
      icloudpd --directory /data
      --cookie-directory /cookies
      --folder-structure {:%Y/%Y-%m-%d}
      --username ${ICLOUDPD_USERNAME}
      --password ${ICLOUDPD_PASSWORD}
      --size original
      --recent ${ICLOUDPD_RECENT:-5000}
      --auto-delete

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          memory: 64M

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    labels:
      - "diun.enable=true"

volumes:
  icloudpd-cookies:
    name: icloudpd
    external: true

networks:
  icloudpd:
    name: icloudpd
    external: true
