server:
    verbosity: 0

    interface: 0.0.0.0
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # Disable IPv6 if you don't have connectivity
    do-ip6: no
    prefer-ip6: no

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization (known to cause DNSSEC issues)
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size (DNS Flag Day 2020 recommendation)
    edns-buffer-size: 1232

    # Prefetch close-to-expired cache entries
    prefetch: yes

    # One thread is sufficient for a homelab
    num-threads: 1

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
